# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keygen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 440)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.pubkey_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.pubkey_browser.setGeometry(QtCore.QRect(40, 50, 491, 131))
        self.pubkey_browser.setObjectName("pubkey_browser")
        self.prikey_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.prikey_browser.setGeometry(QtCore.QRect(40, 220, 491, 161))
        self.prikey_browser.setObjectName("prikey_browser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gen_key_button = QtWidgets.QPushButton(self.centralwidget)
        self.gen_key_button.setGeometry(QtCore.QRect(240, 390, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.gen_key_button.setFont(font)
        self.gen_key_button.setObjectName("gen_key_button")
        Dialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        Dialog.setStatusBar(self.statusbar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MainWindow"))
        self.label.setText(_translate("Dialog", "公钥："))
        self.label_2.setText(_translate("Dialog", "私钥："))
        self.gen_key_button.setText(_translate("Dialog", "生成"))
